# Generated by Django 5.1.5 on 2025-02-01 10:41

from django.db import migrations


def create_default_status(apps, schema_editor):
    Status = apps.get_model("statuses", "Status")
    Status.objects.bulk_create(
        [
            Status(name="Готово"),
            Status(name="В процессе"),
            Status(name="Оплачено"),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_status),
    ]
